### ISSUE TITLE
mdb-schema db.mdb mysql

### ISSUE THREAD

**Issue by shadiakiki1986** [Vaggos/MDBtoMySQL#1]
Hello. Is there a reason why [here](https://github.com/Vaggos/MDBtoMySQL/blob/develop/MDBtoMySQL.sh#L112) you use sed/awk/tr to perform manipulations for converting to mysql syntax instead of passing `mysql` as documented [here](https://github.com/brianb/mdbtools/blob/master/doc/mdb-schema.txt#L31) ?

**Comment by Vagelis-Prokopiou** [comment]
Interesting point @shadiakiki1986. I hadn't noticed this mdbtools option. I will look into it.
